apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-eligibility-config
  namespace: loan-system
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loan_eligibility_db?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
  USER_SERVICE_URL: http://user-management:8081
  SPRING_PROFILES_ACTIVE: docker