apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
  namespace: loan-system
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
  SPRING_PROFILES_ACTIVE: docker